### ISSUE TITLE
Schematic Design

### ISSUE THREAD

**Issue by gabesoares** [sfuphantom/hardware#43]
Design schematic on paper for TSAL, red LED blinking for HV and green solid LED for LV.

**Comment by gabesoares** [comment]
High level block diagram from @Khoideptrai123 :
![44390755_185952375631068_5711581710768930816_n](https://user-images.githubusercontent.com/18123877/47262988-9343f280-d4ab-11e8-8695-873e62a31ca8.jpg)

**Comment by gabesoares** [comment]
@Khoideptrai123 is the schematic in altium finalized? If so please comment with the commit hash in which it was finished.

**Comment by Khoideptrai123** [comment]
[TSAL Circuit-1.pdf.pdf](https://github.com/sfuphantom/hardware/files/3099386/TSAL.Circuit-1.pdf.pdf)
This is the final schematic

**Comment by gabesoares** [comment]
Latest version of schematic almost done, here df24efb
