### ISSUE TITLE
Bill of Materials

### ISSUE THREAD

**Issue by gabesoares** [sfuphantom/hardware#44]
Finalize all parts needed for TSAL circuit

**Comment by gabesoares** [comment]
@Khoideptrai123 @sumreenr is this finalized? If so please comment saying so and close the issue

**Comment by Khoideptrai123** [comment]
The BOM is finished! 

https://docs.google.com/spreadsheets/d/1D_N_h-VSUfupYI5B_tzBBqGqgnA3iFfgFhU_PEmYJnU/edit#gid=0
